### ISSUE TITLE
Make llfio more packager friendly 

### ISSUE THREAD

**Issue by barcharcraz** [ned14/llfio#50] opened 2020-03-07 21:36 UTC
Hi Niall, I mentioned this in Prague, and I know you said there was an open issue, but I couldn't find it. So I'm going to list the issues I had packaging lfio (and cppquicklib) here.

* llfio won't use cppquicklib unless cppquicklib was installed with the default cmakeConfig install path 
(the cppquicklib bootstrap needs to do find_package(cppquicklib CONFIG) and check cppquicklib_FOUND instead of searching through CMKAE_MODULE_PATH for cppquicklib/cmakelib)

* both llfio and cppquick lib need to build without cloning any submodules (this means they need to be able to find their dependencies even if their dependencies headers are not in ${PROJECT_SOURCE_DIR}/include

* cppquicklib and llfio need to be build-able with the same version of their common dependencies

**Comment by ned14** [comment] 2020-03-08 01:05
Since Prague, I believe I have fixed all remaining issues for packaging, at least for cmake hunter. Give the current trunk revision a go and do let me know how it fares for you.

Regarding your first point, we cannot use `find_package()`, because installed quickcpplib doesn't install all the cmake stuff, only the C++ stuff. All the build cmake is kept in quickcpplib, so there is a thin bootstrapper which goes and downloads a copy, then hooks in the cmake and hands off the build. You shouldn't ever find this to be a problem during packaging, if using cmake's standard install mechanisms.

For the second point, for quickcpplib libraries, we do try `find_package()` first, and only if it doesn't work do we go to github. There are some external libs which aren't `find_package()`-eable, and for those we now fetch git submodules if they haven't been checked out.

For the third point, there was a few days there when all of the build was in flux, but that should all be fixed now. To my knowledge, everything is now working, and Travis and Appveyor also say this is so.

**Comment by barcharcraz** [comment] 2020-03-08 04:28
Why can't quickcpplib install the cmake stuff, vcpkg (and debian/fedora and friends) don't permit any network connectivity when downloading.

I'll have a go at packaging tomorrow.

Is there an easy way to tell llfio/quickcpplib's buildsystems to just fail instead of trying to clone said submodules?

**Comment by barcharcraz** [comment] 2020-03-08 05:08
Allright I've opened several issues on quickcpplib that blocked packaging. (the "it writes to the source dir" one doesn't technically block packaging but is super bizarre)

**Comment by ned14** [comment] 2020-03-09 11:34
Firstly, thanks for opening all the individual issues. Secondly, I've made a start on scripting a Travis CI check that quickcpplib libraries work right when installed, which as you correctly discovered, is in fact not currently the case for Outcome.

In terms of bigger picture though, my goals for packaging aren't quite yours. I'm very keen that everything works correctly in terms of cmake install and find package. I'm also keen that cmake hunter works, as that's very popular with the kind of users which are keen on Outcome (i.e. ones with custom toolchains). I'm also keen to retain quickcpplib as an internal implementation library not exposed to the end users of Outcome or LLFIO i.e. I don't want quickcpplib turning up in package managers. And finally, as much as the restamping of revision.hpp may seem bizarre to you, however it's essential because it permutes the ABI. Note that the restamping ought to only occur if you're developing the library, if it thinks it is a dependency, it won't do it (and yes, the detection machinery here is buggy, restamping happens more frequently than it ought to, it is the lack of time to track down and fix the cause as always)

Regarding lack of network access during superbuild which you mentioned in one of your issues, I'll see what I can do. However, all build really is exclusively implemented by quickcpplib, the bootstrap cmake goes and fetches it and then hands off build to it. I'm not minded to change that, as it's very convenient for me to centralise build across all my projects like that. However, equally, I have received complaint from end users whose cmake has had internet access disabled for it, for them the mandatory quickcpplib fetch is really not helpful. So I'll come up with something better than things currently are right now.

That's the big picture, hopefully after all this is done, it will be possible to tell vcpkg et al how to build Outcome. Hopefully by end of this week. Thanks once again for raising all this.

**Comment by ned14** [comment] 2020-03-10 12:05
FYI Outcome now has an Installability CI target: https://travis-ci.org/ned14/outcome/jobs/660581507

From that you should be able to deduce where I'll be going next with LLFIO later this week.

**Comment by barcharcraz** [comment] 2020-03-10 22:19
I get that, I think it's not totally unreasonable to download quickcpplib as part of the build of llfio (it's just annoying).

The main thing is that you can't do network access, so I should be able to download a tarball (or clone) of quickcpplib and plop it into the buildtree before I start building (I think this works)

**Comment by ned14** [comment] 2020-03-11 11:31
Ok, installability CI target is now working. I agree how irritating it is that every dependency is recloned and rebuilt, but that is a cmake hunter quirk. On other package managers where `find_package()` is more sane, it should no longer occur.

(The quickcpplib clone is unavoidable, but you can now set a variable pointing at a pre checked out clone)

**Closed by ned14** 2020-03-11 11:31 UTC

**Comment by BurningEnlightenment** [comment] 2020-03-13 22:28
> The main thing is that you can't do network access, so I should be able to download a tarball (or clone) of quickcpplib and plop it into the buildtree before I start building (I think this works)

I ended up with a way more radical approach: I created seperate vcpkg ports for everything (outcome, nt-kernel-category, quickcpplib, ...) and completely replaced the CMake projects with trimmed down and very straightforward ones. Dependencies are simply resolved via find_package() and abi permutation is disabled.

The necessary somewhat dirty hacks were:
 * needing to patch relative includes (regex replace)
 * needing to patch in a `QUICKCPPLIB_STATIC_LIB` option (well, this is rather optional)
 * the signal guard alternate linker import names aren't combatible with `QUICKCPPLIB_DISABLE_ABI_PERMUTATION` and required some patching

Works surprisingly well so far.

**Comment by ned14** [comment] 2020-03-17 10:02
I fixed the latter two issues at https://github.com/ned14/quickcpplib/commit/b9b21d2af1ebcebea2e78d6c8b1f85a12271a7a0.

Can you tell me more about the "relative includes" requirement?

Regarding your otherwise ease of "simple cmake" build, this I am glad to hear about. It was deliberate that it should be easy. The quickcpplib stuff is mainly about making my personal life easier, and I recognise it does not do this for end users who just want simple cmake. Equally, I don't want to support two lots of cmake either.
