### ISSUE TITLE
span workaround issues

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/llfio#113] opened 2023-02-12 13:45 UTC
Upgrading to latest quickcpplib (82fbebd74a8c372462e2104ab47aa37b7577ca52) broke quite a bit of my code on MSVC 19.34.31937, clang and gcc 11.3:
***
```cpp
/* given */
LLFIO_V2_NAMESPACE::file_handle mRootHandle;
std::span<std::byte> memory;
/* when */
LLFIO_V2_NAMESPACE::file_handle::buffer_type readBuffers[] = {memory};
mRootHandle.read({readBuffers, 0U});
```
doesn't compile anymore
```
  C:\PROGRA~1\MICROS~4\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe  /nologo /TP -DLLFIO_EXPERIMENTAL_STATUS_CODE=1 -DLLFIO_HEADERS_ONLY=0 -DOUTCOME_USE_SYSTEM_STATUS_CODE=1 -DQUICKCPPLIB_ENABLE_VALGRIND=1 -external:I[vcpkg_installed]\x64-windows-static\include -external:W0 /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -MTd /W4 /utf-8 /Zc:__cplusplus -std:c++20 -c mcve.cpp
mcve.cpp(278): error C2440: 'initializing': cannot convert from 'std::span<T,18446744073709551615>' to 'llfio_v2_85eb6946::file_handle::buffer_type'
          with
          [
              T=std::byte
          ]
  mcve.cpp(278): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```
```
/usr/bin/clang++ -DLLFIO_EXPERIMENTAL_STATUS_CODE=1 -DLLFIO_HEADERS_ONLY=0 -DOUTCOME_USE_SYSTEM_STATUS_CODE=1 -DQUICKCPPLIB_ENABLE_VALGRIND=1 -isystem [vcpkg_installed]/x64-linux/include -fconcepts-diagnostics-depth=0 -ftemplate-backtrace-limit=0 -g -fno-omit-frame-pointer -g -Wall -Wextra -std=c++20 -MD -c mcve.cpp
mcve.cpp:278:54: error: no viable conversion from 'std::span<std::byte>' to 'llfio::file_handle::buffer_type' (aka 'llfio_v2_85eb6946::byte_io_multiplexer::buffer_type')
    llfio::file_handle::buffer_type readBuffers[] = {memory};
                                                     ^~~~~~
```
```
/usr/bin/g++ -DLLFIO_EXPERIMENTAL_STATUS_CODE=1 -DLLFIO_HEADERS_ONLY=0 -DOUTCOME_USE_SYSTEM_STATUS_CODE=1 -DQUICKCPPLIB_ENABLE_VALGRIND=1 -isystem [vcpkg_installed]/x64-linux/include -fconcepts-diagnostics-depth=0 -ftemplate-backtrace-limit=0 -g -fno-omit-frame-pointer -g -Wall -Wextra -std=c++20 -MD -c mcve.cpp
mcve.cpp: In function ‘void mcve()’:
mcve.cpp:278:54: error: conversion from ‘std::span<std::byte, 18446744073709551615>’ to non-scalar type ‘llfio_v2_85eb6946::file_handle::buffer_type’ {aka ‘llfio_v2_85eb6946::byte_io_multiplexer::buffer_type’} requested
  278 |     llfio::file_handle::buffer_type readBuffers[] = {memory};
      |                                         
```
same for `const_buffer_type` and `.write()`.

***
The code above can be fixed by
```cpp
LLFIO_V2_NAMESPACE::file_handle::buffer_type readBuffers[] = {{memory}};
```
However, the conversion `std::span<std::byte>` -> `quickcpplib::span<std::byte const>` is still ambiguous:
```cpp
/* given */
LLFIO_V2_NAMESPACE::file_handle mRootHandle
std::span<std::byte> memory;
/* when */
LLFIO_V2_NAMESPACE::file_handle::const_buffer_type writeBuffers[] = {{memory}};
mRootHandle.write({writeBuffers, 0U});
```
```
/usr/bin/g++ -DLLFIO_EXPERIMENTAL_STATUS_CODE=1 -DLLFIO_HEADERS_ONLY=0 -DOUTCOME_USE_SYSTEM_STATUS_CODE=1 -DQUICKCPPLIB_ENABLE_VALGRIND=1 -isystem [vcpkg_installed]/x64-linux/include -fconcepts-diagnostics-depth=0 -ftemplate-backtrace-limit=0 -g -fno-omit-frame-pointer -g -Wall -Wextra -std=c++20 -MD -c mcve.cpp
mcve.cpp: In function ‘void mcve()’:
mcve.cpp:278:61: error: conversion from ‘<brace-enclosed initializer list>’ to ‘llfio_v2_85eb6946::file_handle::const_buffer_type’ {aka ‘llfio_v2_85eb6946::byte_io_multiplexer::const_buffer_type’} is ambiguous
  278 |             = {{memory}};
      |                                      ^
In file included from [vcpkg_installed]/x64-linux/include/llfio/v2.0/byte_io_handle.hpp:28,
                 from [vcpkg_installed]/x64-linux/include/llfio/v2.0/lockable_byte_io_handle.hpp:28,
                 from [vcpkg_installed]/x64-linux/include/llfio/v2.0/file_handle.hpp:28,
                 from [vcpkg_installed]/x64-linux/include/llfio/v2.0/fast_random_file_handle.hpp:28,
                 from [vcpkg_installed]/x64-linux/include/llfio/v2.0/llfio.hpp:69,
                 from [vcpkg_installed]/x64-linux/include/llfio/llfio.hpp:18,
                 from mcve.cpp:8:
[vcpkg_installed]/x64-linux/include/llfio/v2.0/byte_io_multiplexer.hpp:312:15: note: candidate: ‘constexpr llfio_v2_85eb6946::byte_io_multiplexer::const_buffer_type::const_buffer_type(quickcpplib::_776de923::span::span<std::byte>)’
  312 |     constexpr const_buffer_type(span<byte> s) noexcept
      |               ^~~~~~~~~~~~~~~~~
[vcpkg_installed]/x64-linux/include/llfio/v2.0/byte_io_multiplexer.hpp:300:15: note: candidate: ‘constexpr llfio_v2_85eb6946::byte_io_multiplexer::const_buffer_type::const_buffer_type(quickcpplib::_776de923::span::span<const std::byte>)’
  300 |     constexpr const_buffer_type(span<const byte> s) noexcept
      |               ^~~~~~~~~~~~~~~~~
```
(clang++ and msvc fail too)

**Comment by ned14** [comment] 2023-03-01 16:48
Ok I confirmed with a unit test that the issue isn't really fixable via the span wrapper, it'll have to be fixed in LLFIO. I'll try to find some time tomorrow for that.

**Comment by ned14** [comment] 2023-03-09 14:12
Sorry about the slow progress on this. I specifically carved out this morning to look into this in non-work time uninterrupted. And then got interrupted repeatedly, and ended up making no progress. I'll try again next week.

**Closed** 2023-03-11 13:11 UTC

**Comment by ned14** [comment] 2023-03-11 13:13
Managed to get this over the line thanks to my two smallest children being unusually cooperative this morning. Let me know if it doesn't work for you.

**Comment by BurningEnlightenment** [comment] 2023-03-13 09:55
Thanks for fixing this. I'll test this as soon as it enters my package manager's index (https://github.com/microsoft/vcpkg/pull/30149)
