### ISSUE TITLE
CMake configuration fails on Windows using Ninja, clang, MS STL

### ISSUE THREAD

**Issue by vasama** [ned14/llfio#76] opened 2021-04-09 18:22 UTC
The `<filesystem>` check fails without `-std=c++17`, which is only set for MSVC.
I couldn't find any way to force C++17 externally. `-DCMAKE_CXX_STANDARD=17` doesn't work.

**Comment by ned14** [comment] 2021-04-15 10:47
This commit should fix `CMAKE_CXX_STANDARD` not affecting cmake compile probes (I have no idea why cmake doesn't already do this).

I am surprised that cmake would not set `MSVC=1` for `clang-cl`, and thus C++ 17 would be forced on.

**Comment by vasama** [comment] 2021-04-15 14:43
Note that I was using `clang++` - the default for `ninja` - and not `clang-cl`.

**Comment by maksqwe** [comment] 2021-04-16 15:33
I do not create a new issue about vcpkg llfio usage, just asking here, maybe I am wrong with somethimg.
My setup:
- Windows 10
- MSVC 2019 16.9.4
- cmake 3.20.1
So, I installed with latest vcpkg(a267ab118c09f56f3dae96c9a4b3410820ad2f0b) llfio lib:
`vcpkg install llfio[status-code] --triplet=x64-windows`

I created cmake project:
```
cmake_minimum_required(VERSION 3.17)
project(SomeProject)
find_package(llfio CONFIG REQUIRED)
add_executable(main MainProj.cpp)
target_link_libraries(main PRIVATE llfio::hl)
```
then tried to generate msvc project files:
`cmake "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DLLFIO_EXPERIMENTAL_STATUS_CODE=1 -G "Visual Studio 16 2019" -A x64 ..`
And got error messages about Threads::Threads library:
```
CMake Error at D:/rand_repos/vcpkg/scripts/buildsystems/vcpkg.cmake:664 (_add_executable):
  Target "main" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:34 (add_executable)

CMake Error at D:/rand_repos/vcpkg/scripts/buildsystems/vcpkg.cmake:664 (_add_executable):
  Target "main" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:34 (add_executable)

CMake Error at D:/rand_repos/vcpkg/scripts/buildsystems/vcpkg.cmake:664 (_add_executable):
  Target "main" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:34 (add_executable)

CMake Error at D:/rand_repos/vcpkg/scripts/buildsystems/vcpkg.cmake:664 (_add_executable):
  Target "main" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:34 (add_executable)

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
But solution and project file generated successfully, except that linker input list has `Threads::Threads.lib` that can bot be found during linkage. Removing Threads::Threads.lib helps compile and run project.

Is it vcpkg port issue or something I am doing wrong?

**Comment by ned14** [comment] 2021-04-16 16:01
> But solution and project file generated successfully, except that linker input list has Threads::Threads.lib that can not be found during linkage. Removing Threads::Threads.lib helps to compile and run project.

It's because you use the `::hl` target, which is all header only, so the cmake link libraries exported by the `::hl` includes `Threads::Threads` because your final application needs to include a threading library. `FindThreads()` from cmake would fix it. See https://cmake.org/cmake/help/latest/module/FindThreads.html

(I know that in standard MSVC `Threads::Threads` is redundant, but it wouldn't be if you were on mingw or something)

**Comment by ned14** [comment] 2021-04-19 09:58
Assuming that non-clang-cl usage is not common on Windows, and there is a viable workaround now, closing. Let me know if the problem isn't actually resolved.

**Closed by ned14** 2021-04-19 09:58 UTC
